export default {
  ACCOUNT_CHANGED: '@@RELIKE/ACCOUNT_CHANGED',

  DISLIKE: '@@RELIKE/DISLIKE',
  DISLIKE_ERROR: '@@RELIKE/DISLIKE_ERROR',
  DISLIKE_START: '@@RELIKE/DISLIKE_START',
  DISLIKE_SUCCESS: '@@RELIKE/DISLIKE_SUCCESS',

  GET_LIKE_COUNT: '@@RELIKE/GET_LIKE_COUNT',
  GET_LIKE_COUNT_ERROR: '@@RELIKE/GET_LIKE_COUNT_ERROR',
  GET_LIKE_COUNT_START: '@@RELIKE/GET_LIKE_COUNT_START',
  GET_LIKE_COUNT_SUCCESS: '@@RELIKE/GET_LIKE_COUNT_SUCCESS',

  GET_LIKE_DATA: '@@RELIKE/GET_LIKE_DATA',
  GET_LIKE_DATA_ERROR: '@@RELIKE/GET_LIKE_DATA_ERROR',
  GET_LIKE_DATA_START: '@@RELIKE/GET_LIKE_DATA_START',
  GET_LIKE_DATA_SUCCESS: '@@RELIKE/GET_LIKE_DATA_SUCCESS',

  GET_MY_RATING: '@@RELIKE/GET_MY_RATING',
  GET_MY_RATING_ERROR: '@@RELIKE/GET_MY_RATING_ERROR',
  GET_MY_RATING_START: '@@RELIKE/GET_MY_RATING_START',
  GET_MY_RATING_SUCCESS: '@@RELIKE/GET_MY_RATING_SUCCESS',

  LIKE: '@@RELIKE/LIKE',
  LIKE_ERROR: '@@RELIKE/LIKE_ERROR',
  LIKE_START: '@@RELIKE/LIKE_START',
  LIKE_SUCCESS: '@@RELIKE/LIKE_SUCCESS',

  NEW_LIKE: '@@RELIKE/NEW_LIKE',

  UNDISLIKE: '@@RELIKE/UNDISLIKE',
  UNDISLIKE_ERROR: '@@RELIKE/UNDISLIKE_ERROR',
  UNDISLIKE_START: '@@RELIKE/UNDISLIKE_START',
  UNDISLIKE_SUCCESS: '@@RELIKE/UNDISLIKE_SUCCESS',

  UNLIKE: '@@RELIKE/UNLIKE',
  UNLIKE_ERROR: '@@RELIKE/UNLIKE_ERROR',
  UNLIKE_START: '@@RELIKE/UNLIKE_START',
  UNLIKE_SUCCESS: '@@RELIKE/UNLIKE_SUCCESS',
};
